export type IconName =
  | 'home'
  | 'person'
  | 'mail'
  | 'addOutline'
  | 'lockClosed'
  | 'searchOutline'
  | 'heartOutline'
  | 'heart'
  | 'shareSocialOutline'
  | 'settingsOutline'
  | 'eye'
  | 'notificationsOutline'
  | 'chatboxEllipsesOutline'
  | 'eyeOff'
  | 'logoGoogle'
  | 'logoGithub'
